// communesData.js

export const communes = [
    {
      name: "Ratoma",
      quartiers: [
        "Taouyah",
        "Ratoma Dispensaire",
        "Ratoma Centre",
        "Kaporo Rails",
        "Hamdallaye 1",
        "Hamdallaye 2",
        "Koloma Soloprimo",
        "Kipé",
        "Kaporo Centre",
      ],
    },
    {
      name: "Lambanyi",
      quartiers: [
        "Nongo-centre",
        "Nongo Taady",
        "Lambanyi",
        "Yembeya",
        "Waréah",
        "Simbaya Gare",
        "Yattaya centre",
        "Nassouroulaye",
        "Bantounka 1",
        "Bantounka 2",
        "Soumambossia",
        "Wanindara",
        "Wanindara Rails",
        "Kinifi",
      ],
    },
    {
      name: "Sonfonia",
      quartiers: [
        "Kobayah",
        "Yattaya Fossidet",
        "Yattaya centre",
        "Sonfonia Gare 1",
        "Sonfonia Gare 2",
        "Sonfonia Centre 1",
        "Sonfonia Centre 2",
      ],
    },
    {
      name: "Gbessia",
      quartiers: [
        "Dabondy 1",
        "Dabondy 2",
        "Dabondy 3",
        "Dabondy Ecole",
        "Dabondy Rails",
        "Gbessia Cité 1",
        "Gbessia Cité 2",
        "Gbessia Cité 3",
        "Gbessia Ecole",
        "Gbessia Centre",
        "Gbessia Port 1",
        "Gbessia Port 2",
        "Dar-Es-Salam",
        "Cité de l’air",
        "Béhanzin",
        "Tanènè Marché",
        "Tanènè Mosquée",
        "Yimbaya Ecole",
        "Yimbaya Permanence",
        "Yimbaya Port",
        "Hamdallaye Mosquée",
        "Yimbaya Tannerie",
        "Simbaya 1",
        "Koloma 1",
        "Koloma 2",
        "Nassouroulaye",
      ],
    },
    {
      name: "Matoto",
      quartiers: [
        "Matato Centre",
        "Simbaya 2",
        "Simbaya Ecole",
        "Matoto Marché",
        "Matoto Khabitaya",
        "Sangoyah Mosquée",
        "Sangoyah Marché",
        "Kissosso",
        "Kissosso Plateau",
        "Marché Enco 5",
        "Wanindara Dispensaire",
        "Wanindara Marché",
      ],
    },
    {
      name: "Tombolia",
      quartiers: [
        "Enta Marché",
        "Enta Fassa",
        "Tombolia",
        "Tombolia Plateau",
        "Dabompa Village",
        "Dabompa Plateau",
        "Lansanayah",
      ],
    },
  ];
  